dataset_args:
  dataset_name: cifar10
  data_path: /data/tfliu/dataset
  zca: True

model_args:
  modelname: convnet3

opt_args:
  opt_name: 'adam'
  lr: 0.001

expert_module_args:
  module_name: 'clfmodule'
  module_args:
    aug_args:
      strategy: 'color_crop_cutout_flip_scale_rotate'

buffer_folder_name: assets/buffers/convnet3zca_0to7_itv1
repeat: 100
max_epoch: 8
buffer_interval: 1
