exp_config:
  project: BPTT
  exp_name: lbrtgtclfdd-rat-200-60-10ipc
  seed: 0
  use_wandb: True
  wandb_api_key: 
  num_steps: 100000
  device: 'cuda'

dataset_config:
  dataset_name: cifar10
  data_path: /data/tfliu/dataset
  zca: False

synset_config:
  synset_type: imagelabelertargetsynset
  synset_args: 
    ipc: 10
    labeler_args:
      modelname: convnet3
    labeler_path: 'assets/conv3_stdt.pt'
    train_images: True
    train_labeler: False
    init_type: 'noise_normal'
    augment_args:
      strategy: 'flip_rotate'
      batch: True
  synset_opt_args:
    images:
      opt_name: adam
      lr: 0.001
    ema_grad_clip: True
    ema_coef: 0.9

eval_config:
  eval_interval: 100
  num_eval: 3
  eval_models:
    conv3:
      model_args:
        modelname: convnet3
      opt_args:
        opt_name: 'adam'
        lr: 0.001
  eval_steps: 1000
  eval_batchsize: 1024
  eval_train_module_args:
    module_name: clflbrtgtmodule
    module_args:
      aug_args:
        strategy: ''
      label_weight: 0.01
  eval_test_module_args:
    module_name: clfmodule
    module_args:
      aug_args:
        strategy: ''
  upload_visualize: True
  upload_visualize_interval: 100
  save_visualize: True
  save_visualize_interval: 100

loop_config:
  bptt_type: rat_bptt
  num_forward: 200
  num_backward: 60
  meta_loss_batchsize: 1024
  inner_loop_config:
    inner_loop_type: clf
    inner_loop_args:
      inner_module_args:
        module_name: clflbrtgtmodule
        module_args:
          aug_args:
            strategy: ''
          label_weight: 0.01
      inner_model_args:
        modelname: 'convnet3'
      inner_opt_args:
        opt_name: adam
        lr: 0.001
      inner_batch_size: 100
      data_per_loop: 5000
      external_module_args:
        module_name: clfmodule
        module_args:
          aug_args:
            strategy: 'flip_rotate'
      external_batch_size: 2500