exp_config:
  project: BPTT
  exp_name: multiclfdd-unbatched-fliprotate-rat-200-60-zca-10ipc
  seed: 0
  use_wandb: False
  wandb_api_key: 
  num_steps: 100000
  device: 'cuda'

dataset_config:
  dataset_name: cifar10
  data_path: /data/tfliu/dataset
  zca: True

synset_config:
  synset_type: imagelabsynset
  synset_args: 
    ipc: 10
    train_images: True
    train_targets: True
    init_type: 'noise_normal'
    augment_args:
      strategy: 'flip_rotate'
      batch: False
  synset_opt_args:
    images:
      opt_name: adam
      lr: 0.005
    targets:
      opt_name: adam
      lr: 0.005
    ema_grad_clip: True
    ema_coef: 0.9

eval_config:
  eval_interval: 100
  num_eval: 3
  eval_models:
    conv3:
      model_args:
        modelname: convnet3
      opt_args:
        opt_name: 'adam'
        lr: 0.001
  eval_steps: 1000
  eval_batchsize: 1024
  eval_train_module_args:
    module_name: clfmodule
    module_args:
      aug_args:
        strategy: ''
  eval_test_module_args:
    module_name: clfmodule
    module_args:
      aug_args:
        strategy: ''
  upload_visualize: True
  upload_visualize_interval: 100
  save_visualize: True
  save_visualize_interval: 100

loop_config:
  bptt_type: bptt
  num_forward: 200
  num_backward: 200
  meta_loss_batchsize: 1024
  inner_loop_config:
    inner_loop_type: clf
    inner_loop_args:
      inner_module_args:
        module_name: clfmodule
        module_args:
          aug_args:
            strategy: ''
      inner_model_args:
        modelname: 'convnet3'
      inner_opt_args:
        opt_name: adam
        lr: 0.001
      inner_batch_size: 100
      data_per_loop: 5000
      external_module_args:
        module_name: clfmodule
        module_args:
          aug_args:
            strategy: 'flip_rotate'
      external_batch_size: 2500
      num_meta_loss: 5
      min_steps: 60